# Quantitative Scoring Configuration
quantitative_scoring:
  metrics:
    Alpha (Since Inception): { weight: 20, higher_is_better: true } # Increased from 15
    'Historical Sharpe Ratio (3Y)': { weight: 15, higher_is_better: true } # Increased from 10
    'Historical Sharpe Ratio (5Y)': { weight: 10, higher_is_better: true }
    'Information Ratio (vs Category) (3Y)': { weight: 10, higher_is_better: true }
    'Information Ratio (vs Category) (5Y)': { weight: 10, higher_is_better: true }
    'Max Drawdown (3Y)': { weight: 10, higher_is_better: false }
    'Max Drawdown (5Y)': { weight: 10, higher_is_better: false } # Corrected from 5
    'Daily Value at Risk (VaR) 5% (3Y Lookback)': { weight: 5, higher_is_better: false }
    'Batting Average (3Y Lookback)': { weight: 5, higher_is_better: true }
    'Upside/Downside Ratio (3Y)': { weight: 5, higher_is_better: true }
  penalties:
    'Max Drawdown (3Y)': { apply: true, threshold: -0.35, penalty_points: 5 }

# Qualitative Scoring Configuration
qualitative_scoring:
  weights:
    'Team Depth': 25
    'Transparency & Reporting': 15
    'Investment Philosophy Clarity': 20
    'Consistency of Process': 40
  score_mapping:
    'High': 3
    'Medium-High': 2.5
    'Medium': 2
    'Clear': 2 # For 'Investment Philosophy Clarity'
    'Strong': 3 # For 'Consistency of Process'
    'Moderate': 1.5
    'Developing': 1
    'Low': 0
    # Add other specific text values found in the data
    'ESG-aware growth investing': 2.5
    'Quality growth across cycles': 3
    'Value-oriented, fundamentals-based': 3
    'Quantitative growth w/ fundamental overlay': 2.5
    'Dividend growth across market caps': 2.5
    'Concentrated value portfolio': 2
    '3S Framework – Structural, Sustainable, Stewardship': 3

# Score Combination Configuration
combination_config:
  qualitative_weight: 0.40
  quantitative_weight: 0.60

# Tiering Configuration (for reference, now handled in app.py)
tier_config:
  tier1_cutoff: 80
  tier2_cutoff: 60